# Generated by Django 4.2.8 on 2023-12-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='no_passengers',
            new_name='no_of_passengers',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='user',
        ),
    ]
