# Generated by Django 4.2.8 on 2023-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='airline_name',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airline',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
    ]
