# Generated by Django 4.2.8 on 2023-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_aircraft_airline_name_aircraft_airline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='airline',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.CharField(max_length=30),
        ),
    ]
