# Generated by Django 4.2.8 on 2023-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_airline_aircraft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
    ]
